chore: added dependabot setup, removed unnecessary inputs from workfl…
Informasjonsforvaltning/fdk-dataset-preview-service pull request #17
Opened 2022-11-01 15:42 UTC by valosnah

…ows, updated deps

2022-11-02 07:09 UTC, NilsOveTen submitted a review, later dismissed

2022-11-02 07:09 UTC, NilsOveTen commented on pom.xml
>          <jena.version>4.5.0</jena.version>
```suggestion
        <jena.version>4.6.1</jena.version>
```

2022-11-02 13:57 UTC, jeffreiffers requested changes

2022-11-02 13:57 UTC, jeffreiffers commented on pom.xml
>              <artifactId>micrometer-registry-statsd</artifactId>
statsd kan erstattes med prometheus, også konfig endring

2022-11-04 09:56 UTC, valosnah commented on pom.xml
>          <jena.version>4.5.0</jena.version>
fixd

2022-11-04 09:56 UTC, valosnah commented on pom.xml
>              <artifactId>micrometer-registry-statsd</artifactId>
fixd

2022-11-07 12:42 UTC, NilsOveTen approved these changes

2022-11-07 13:55 UTC, merged